### ISSUE TITLE
No streaming, no downloads

### ISSUE THREAD

**Issue by Managrmny** [mikew/ss-plex.bundle#65] opened 2017-04-20 03:38 UTC
For the past 2 days many people are experiencing problems not being able to stream or download via ss plex.

**Comment by brock0lee** [comment] 2017-04-20 16:59
Has anyone heard of any solution to this or found the cause?  I've been spoiled by the Watch Later feature and need it back!  Please don't make me go back to manually searching for shows and movies!

**Comment by FarFromNormal** [comment] 2017-04-20 21:42
Same issue here.

**Comment by zaphod765** [comment] 2017-04-21 00:10
Same issue; getting "server DNS address could not be found" error on all shows & movies on watch now, have tried all the various sources.  Let me know if I can help with testing? Thx -

**Comment by mikew** [comment] 2017-04-21 01:32
Working on a fix now. The back end has been pretty neglected.

**Comment by swiftvic** [comment] 2017-04-21 01:35
I'm having the same issue with ss plex but looks like primewire is not working either.
Not sure if the new plex update had anything to do with it? I'm running flex off my Synology NAS DS214play.

**Comment by mikew** [comment] 2017-04-21 04:28
I've pushed the changes: 

- refreshed providers 
- added a couple of new sites 

Let me know if estream is working for you. I'm getting SSL errors my end.

**Comment by mikew** [comment] 2017-04-21 04:30
Also: Go to System > Reset > Cache to get the latest procedures earlier.

**Comment by Managrmny** [comment] 2017-04-21 05:09
New sources working. Thanks for the update Mike.

**Comment by zaphod765** [comment] 2017-04-21 05:53
Yes!  Shows and movies now working on Roku, OSX, and Android. 
Thank you very much!  
I'm always willing to beta if you need it. 
Mike, you rock!

**Comment by swiftvic** [comment] 2017-04-21 11:45
Confirmed, working for me as well.
Thanks Mike, you are awesome!

**Comment by brock0lee** [comment] 2017-04-21 12:19
It's working for one show via teh Retry Download option.  After it complete's I'm going to try the Repair Downloads option to take care of all of the rest to see what happens.  I'll let you know my results.  Let me know if you want any log files from my end.

Thanks Mike!  SS-Plex is the only app I use on my Plex because it's the only one I need.

**Comment by brock0lee** [comment] 2017-04-21 13:13
I get Connection error HTTP error code 404 when I try to use the Repair Downloads option.  I can go into each failed download and use the Retry Download option though.

**Comment by mikew** [comment] 2017-04-21 17:26
"Repair downloads" is to kick the channel out of some strange state it can get in. As you found out, you have to manually retry each download.

**Comment by mikew** [comment] 2017-04-22 19:36
Closing since things are stable now

**Closed as completed by mikew** 2017-04-22 19:36 UTC

**Comment by schieving** [comment] 2017-05-21 05:51
I know this is closed but I just updated to plex 1.5.6.3790 and I have also updated to the latest ss-plex and I have reset sources and cache and everything and still all my download/watch later fail.  What am I missing?
